apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-hello
spec:
  containers:
  - name: hello
    image: no2a/hello
    livenessProbe:
      httpGet:
        path: /liveness
        port: 3000
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 3000
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 3
